name: Create release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target=vkhandybug.AppImage
    - name: upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.os}}-binary
        path: ${{github.workspace}}/build/bin/vkhandybug.AppImage
        
  Flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt -y install make autoconf gcc cmake libvulkan-dev git libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev glslang-tools mesa-common-dev libfuse2 flatpak flatpak-builder
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: io.github.lleny.vkhandybug.flatpak
        manifest-path: io.github.lleny.vkhandybug.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.os}}-binary
        path: ${{github.workspace}}/io.github.lleny.vkhandybug.flatpak


