name: Create release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt -y install make autoconf gcc cmake libvulkan-dev git libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev glslang-tools mesa-common-dev libfuse2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target=vkhandybug.AppImage
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vkhandybug.AppImage
        path: ${{github.workspace}}/build/bin/vkhandybug.AppImage
        
  Flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt -y install make autoconf gcc cmake libvulkan-dev git libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev glslang-tools mesa-common-dev libfuse2 flatpak flatpak-builder
    - name: Add flathub
      run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install flatpak dependencies
      run: flatpak install --user --assumeyes flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08 org.freedesktop.Platform.GL.default/x86_64/22.08
    - name: Build
      run: flatpak-builder --user --force-clean flatpak io.github.lleny.vkhandybug.yml
    - name: Export
      run: flatpak build-export flatpak-export flatpak
    - name: Bundle
      run: flatpak build-bundle flatpak-export io.github.lleny.vkhandybug.flatpak io.github.lleny.vkhandybug
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: io.github.lleny.vkhandybug.flatpak
        path: ${{github.workspace}}/io.github.lleny.vkhandybug.flatpak
